"""Added new fields in the Users Table Model

Revision ID: 00130f759ac4
Revises: 4340a9eb665b
Create Date: 2024-04-13 17:51:03.155794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00130f759ac4'
down_revision = '4340a9eb665b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
