"""Added language fields to the Post table

Revision ID: 1378a25cf4ae
Revises: 8568c3dbfe77
Create Date: 2024-05-25 17:41:47.315316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1378a25cf4ae'
down_revision = '8568c3dbfe77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
